apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  labels:
    tier: backend
    app: fleet-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      # Optional field,
      nodePort: 30083
  selector:
    api: fleet-service
