apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    api: user-service
    app: user-service
spec:
  containers:
    - name: users
      image: quarkus/users:1.0
      ports:
        - containerPort: 8083
          name: http
          protocol: TCP
      env:
        - name: JAEGER_ENDPOINT
          value: "http://jaeger-collector.observability:14268/api/traces"