apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    tier: backend
    app: user-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      # Optional field,
      nodePort: 30082
  selector:
    api: user-service